# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Step 1 -  Use Node.js ${{ matrix.node-version }}, build design tokens
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build:tokens -- --theme=light
      - run: npm run build:tokens -- --theme=dark
      - run: npm run build:tokens -- --theme=brandone

      - name: Step 2 - Use the Upload Artifact GitHub Action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Upload new design tokens
